---
kind: pipeline
type: kubernetes
name: test

trigger:
  event:
    - push
    - pull_request
    - tag

workspace:
  path: /go/src/github.com/${DRONE_REPO}

volumes:
  - name: cache
    temp: {}

steps:
  - name: test
    image: golangci/golangci-lint:v1.61.0-alpine
    volumes:
      - name: cache
        path: /go
    commands:
      - apk add make
      - make test

  - name: license-check
    image: public.ecr.aws/kanopy/licensed-go:4.0.4-0.3.0
    commands:
      - licensed cache
      - licensed status

  - name: build
    image: plugins/kaniko-ecr
    volumes:
      - name: cache
        path: /go
    pull: always
    settings:
      no_push: true
    when:
      event: [pull_request]

---
kind: pipeline
name: publish-push-amd64
platform:
  arch: amd64

depends_on:
  - test

trigger:
  event: [push]

steps:
  - name: publish
    image: plugins/kaniko-ecr
    settings:
      registry: public.ecr.aws/kanopy
      repo: ${DRONE_REPO_NAME}
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}-amd64
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key

---
kind: pipeline
name: publish-push-arm64
platform:
  arch: arm64

depends_on:
  - test

trigger:
  event: [push]

steps:
  - name: publish
    image: plugins/kaniko-ecr
    settings:
      registry: public.ecr.aws/kanopy
      repo: ${DRONE_REPO_NAME}
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}-arm64
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
---
kind: pipeline
name: publish-tag-amd64
platform:
  arch: amd64

depends_on:
  - test

trigger:
  branch: main
  event: [tag]

steps:
  - name: publish
    image: plugins/kaniko-ecr
    settings:
      registry: public.ecr.aws/kanopy
      repo: ${DRONE_REPO_NAME}
      auto_tag: true
      auto_tag_suffix: amd64
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key

---
kind: pipeline
name: publish-tag-arm64
platform:
  arch: arm64

depends_on:
  - test

trigger:
  branch: main
  event: [tag]

steps:
  - name: publish
    image: plugins/kaniko-ecr
    settings:
      registry: public.ecr.aws/kanopy
      repo: ${DRONE_REPO_NAME}
      auto_tag: true
      auto_tag_suffix: arm64
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
