---
kind: pipeline
type: kubernetes
name: default

workspace:
  path: /go/src/github.com/${DRONE_REPO}

steps:
  - name: test
    image: golangci/golangci-lint:v1.38.0-alpine
    commands:
      - apk add make
      - make test

  - name: build
    image: plugins/kaniko-ecr
    settings:
      no_push: true
    when:
      event: [pull_request]

  - name: publish
    image: plugins/kaniko-ecr
    settings:
      registry: public.ecr.aws/kanopy-sandbox
      repo: ${DRONE_REPO_NAME}
      create_repository: true
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event: [push]

  - name: publish-tag
    image: plugins/kaniko-ecr
    settings:
      registry: public.ecr.aws/kanopy-sandbox
      repo: ${DRONE_REPO_NAME}
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - ${DRONE_TAG}
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event: [tag]
