---
kind: pipeline
type: kubernetes
name: default

trigger:
  event: [push, tag]

workspace:
  path: /go/src/github.com/${DRONE_REPO}

steps:
  - name: test
    image: golangci/golangci-lint:v1.38.0-alpine
    commands:
      - apk add make
      - make test

  - name: publish
    image: plugins/kaniko-ecr
    settings:
      registry: public.ecr.aws
      repo: kanopy-sandbox/${DRONE_REPO_NAME}
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key

  - name: publish-tag
    image: plugins/ecr
    settings:
      repo: ${DRONE_REPO_NAME}
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - ${DRONE_TAG}
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event:
        - tag
